### ISSUE TITLE
Butt ton of PHP warnings and notices on page creation

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/client-dash-admin-pages#1]
This goes on pretty far down:
![Screen Shot 2017-02-20 at 3.59.11 PM](http://static.gitscout.com/53fc5520a4f675264c4ead4707088c277499ea37132daff347083c2221e1f547.png)

Looks like it is because it is throwing a warning and a notice for every single registered capability.

**Comment by brashrebel** [comment]
Possibly related: the CD notice about roles changing or whatever isn't going away even after I saved the Display Settings.

**Comment by joelworsham** [comment]
DANG

**Comment by joelworsham** [comment]
I regret ever making that admin error... I'm going to remove it in the next CD update

**Comment by joelworsham** [comment]
These gone now?

**Comment by brashrebel** [comment]
Yes
