### ISSUE TITLE
More intuitive position UI

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/client-dash-admin-pages#4]
At some point it would be cool to introduce some UI that is a little nicer than simply setting a number. Users have no idea what the number means and it doesn't really work exactly the way they'll expect anyway. Should be acceptable for now but we should make it better in the future.

You know...now that I think more about it...I'm wondering if that's right. Do we really need the position setting at all right now? I'm almost thinking we should go with no option for that and just setting the number automatically since they can use the menu management feature to move it if they want. Either that or actually going the distance of creating a nice, intuitive option for setting position from the get go.

Thoughts?

**Comment by joelworsham** [comment]
Well, I did at least add the codex explanation in the field description, but I know it's quite underwhelming.

I had thought it might be good to improve it, but you're right that the menu management might be a better solution... Perhaps leaving it like it is now isn't so bad because most might ignore it and use menu management anyways?

**Comment by brashrebel** [comment]
I'm on the fence. We can remove it and set it to a static number which would force users to use the menu management feature if they want it somewhere else. We could leave it which means there will exist two controls and increases potential for user confusion but would allow some level of control for users not employing the menu management feature. We could go the distance of making a nicer position management feature...

I'll defer to your judgement on this. I guess if it were up to me I'd lean towards leaving it out.
