### ISSUE TITLE
Page styling

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/client-dash-admin-pages#5]
After messing with the admin pages and viewing them, I've been thinking about how they could be made to look a bit nicer. There isn't much precedence for pages with lots of text and other content in the wp-admin so we're kind of figuring this out on our own. However I think the pages right now don't look awesome.
![Screen Shot 2017-02-21 at 9.33.15 AM](http://static.gitscout.com/aa4014fb058c3212fe9bd61a2cdd51a1d08362d9e65721a41ef6e45426ffee4e.png)
What's happening is cool but it doesn't look very nice. After browsing through the wp-admin I was thinking, what if we modeled after the container on the Tools page? Might look something like this:
![Screen Shot 2017-02-21 at 9.36.07 AM](http://static.gitscout.com/e053c28d955001cfb7a5076419009f32b8f3c1361262488e8e710170cf5bd2c4.png)
That is just simply using the `.card` class on the container. It might need some extra styling to make elements like the video embed fit (I had to manually shrink it to keep it from spilling out of the card) but otherwise it looks a bit nicer.

Thoughts?

**Comment by joelworsham** [comment]
Yeah I dig it. Let's do it. We can always brainstorm more intuitive ideas later.

**Comment by brashrebel** [comment]
Or maybe....we could have some kind of simple option on the edit page. Similar experience to the Page Template select field which exists for pages by default. We could support a couple different page styles.

Probably though 1.0 should just stick with the nicest looking for now. We could have alternative styles supported in a future version.
